<script src="<?php base_url()?>assets/js/bootstrap-select.js"></script>
<script src="<?php base_url()?>assets/js/YouTubePopUp.jquery.js"></script>
<script src="<?php base_url()?>assets/js/jquery.fancybox.pack.js"></script>
<script src="<?php base_url()?>assets/js/jquery.fancybox-media.js"></script>
<script src="<?php base_url()?>assets/js/owl.js"></script>
<script src="<?php base_url()?>assets/js/mixitup.js"></script>
<script src="<?php base_url()?>assets/js/wow.js"></script>
<script src="<?php base_url()?>assets/js/jshashtable-2.1_src.js"></script>
<script src="<?php base_url()?>assets/js/jquery.numberformatter-1.2.3.js"></script>
<script src="<?php base_url()?>assets/js/tmpl.js"></script>
<script src="<?php base_url()?>assets/js/jquery.dependClass-0.1.js"></script>
<script src="<?php base_url()?>assets/js/draggable-0.1.js"></script>
<!-- <script src="<?php base_url()?>assets/js/jquery.slider.js"></script> -->